---
title: "p8105_hw5_hx2264"
author: "Hongyao Xie"
date: "November 3, 2018"
output: github_document
---

## Problem 1

```{r}
library(tidyverse)
```

```{r}
files <- list.files(path = "./data/", pattern = "*.csv")

read_file <- function(x) {
  read.csv(paste0("./data/", x))
}

df <- files %>% 
  map(read_file) %>%
  reduce(rbind) %>% 
  janitor::clean_names()
  
df$arm <- c(rep("con",10), rep("exp",10))
df$id <- c(rep(1:10,2))
df$arm_id = paste(df$arm, df$id, sep = "_")

df <- df %>%
  gather(key = week, value = data, week_1:week_8)

df %>% 
  group_by(arm_id) %>% 
  ggplot(aes(x = week, y = data)) + 
    geom_line(aes(colour = arm_id, group = arm_id, linetype = arm)) +
    theme(legend.position = "bottom") +
    labs(
      title = "Spaghetti plot of observations on each subject over week",
      x = "Week",
      y = "Observations of each subject"
    )
```


## Problem 2

```{r}
homic <-  read_csv("homicide_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(city_state = paste(city, state, sep = ",")) 

homic_summary <- homic %>% 
  group_by(city_state) %>% 
  mutate(total = n()) %>%
  filter(disposition == "Closed without arrest" |
           disposition == "Open/No arrest") %>% 
  mutate(unsolve = n()) %>% 
  group_by(city_state, total, unsolve) %>% 
  summarize()
homic_summary

btm <- homic_summary %>% 
  filter(city_state == "Baltimore,MD")

btm_prop <- prop.test(btm$unsolve, btm$total) %>% 
  broom::tidy() %>% 
  select(estimate, conf.low, conf.high)
```



```{r}
map2(.x = homic_summary$unsolve, .y = homic_summary$total, ~prop.test(.x, .y))
```
















